name: my_streamlit_app
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.8
  - streamlit=1.20.0
  - torch==1.10.0
  - torchvision==0.11.1
  - clip==1.0.1
  - pillow==8.3.2
  - lightning==1.5.0
  - numpy==1.21.2
